# Generated by Django 5.2.4 on 2025-06-08 05:00
from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_platformuser_contact_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSearchQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "remaining",
                    models.PositiveIntegerField(default=0),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_quota",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
