version: '3.8'


services:
  web:
    build: ./backend
    container_name: breachhawk_web
    ports:
      - "8000:8000"
    volumes:
      - ./backend/django_project:/app
    env_file:
      - .env.example
    environment:
      - PYTHONPATH=/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - mongo

  db:
    image: postgres:15
    container_name: breachhawk_db
    env_file:
      - .env.example
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6.0
    container_name: breachhawk_mongo
    env_file:
      - .env.example
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro

volumes:
  postgres_data:
  mongo_data:
