services:
  redis:
    image: redis:7
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: breach_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  tor:
    build: ./proxy/tor        # usa a imagem que você acabou de criar
    container_name: tor
    restart: unless-stopped
    ports:
      - "9050:9050"
      - "9051:9051"

  backend-worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    command: celery -A breachhawk.celery worker -Ofair -l info
    depends_on:
      - backend
      - redis
      - tor
    env_file:
      - .env
    environment:
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright


  backend-beat:
    build:
      context: .
      dockerfile: worker/Dockerfile
    command: celery -A breachhawk.celery beat -l info
    env_file:
      - .env
    depends_on:
      - backend
      - backend-worker

  mongo:
    image: mongo:8
    restart: always
    env_file:
      - .env
    volumes:
      - ./mongodata:/data/db
      - ./mongo:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"

volumes:
  pgdata:
  mongodata: