# Generated by Django 5.2.2 on 2025-06-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="monthly_revenue",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="domain",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
