# Generated by Django 5.2.2 on 2025-06-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrapers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="snapshot",
            name="screenshot",
            field=models.BinaryField(default=bytes),
        ),
    ]
