# Generated by Django 5.2.2 on 2025-06-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Leak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=255)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("found_at", models.DateTimeField(auto_now_add=True)),
                ("source_url", models.URLField()),
            ],
            options={
                "ordering": ["-found_at"],
                "unique_together": {("company", "source_url")},
            },
        ),
    ]
