# Generated by Django 5.2.2 on 2025-06-08 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaks", "0001_initial"),
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leak",
            name="amount_of_data",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="leak",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leak",
            name="download_links",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leak",
            name="information",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leak",
            name="publication_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leak",
            name="rar_password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="leak",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sites.site",
            ),
        ),
        migrations.AddField(
            model_name="leak",
            name="views",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
