# Generated by Django 5.2.2 on 2025-06-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_id", models.CharField(max_length=255)),
                ("customer", models.CharField(blank=True, max_length=255, null=True)),
                ("amount_due", models.IntegerField()),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("due_date", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_id", models.CharField(max_length=255)),
                ("amount", models.IntegerField()),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("created", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_id", models.CharField(max_length=255)),
                ("customer", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("current_period_end", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
