# Generated by Django 5.2.2 on 2025-06-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("links", models.JSONField(default=list)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("forum", "Forum"),
                            ("website", "Website"),
                            ("telegram", "Telegram"),
                            ("discord", "Discord"),
                            ("paste", "Paste"),
                        ],
                        default="website",
                        max_length=20,
                    ),
                ),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("basic", "Basic"),
                            ("form", "Form"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "captcha_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("image", "Image"),
                            ("math", "Math"),
                            ("rotated", "Rotated"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("scraper", models.CharField(default="generic", max_length=255)),
                ("needs_js", models.BooleanField(default=False)),
                ("bypass_config", models.JSONField(blank=True, null=True)),
                ("credentials", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
