# Generated by Django 5.2.2 on 2025-06-08 04:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_id", models.IntegerField()),
                ("api_hash", models.CharField(max_length=255)),
                ("session_string", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="site",
            name="links",
        ),
        migrations.AddField(
            model_name="site",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="site",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="site",
            name="url",
            field=models.URLField(default="", unique=True),
        ),
        migrations.CreateModel(
            name="SiteMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("retries", models.IntegerField(default=0)),
                ("permanent_fail", models.BooleanField(default=False)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.site"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="site",
            name="telegram_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sites.telegramaccount",
            ),
        ),
        migrations.CreateModel(
            name="SiteLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(default="", unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "unique_together": {("site", "url")},
            },
        ),
    ]
