# Generated by Django 5.2.3 on 2025-06-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_telegramaccount_remove_site_links_site_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramaccount",
            name="phone",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
