# Generated by Django 5.2.4 on 2025-07-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0004_make_url_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="frequency_minutes",
            field=models.PositiveIntegerField(default=60),
        ),
    ]
